version: '3.9'

services:

  api:
    # container_name: nodejs_api
    build: .
    # ports:
    # - 4000:4000
  nginx: 
    image: nginx:latest
    volumes: 
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api 
    ports: 
      - 7000:4000
