# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: AKIA5RHLXW4LDPEL4DFD
        secret_access_key: 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
        account_id: 930354804502
        repo: docker/repo
        region: us-west-1
        tags: latest,${{ github.sha }}
        create_repo: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

